### ISSUE TITLE
feature request: subfiled border plotting in python

### ISSUE THREAD

**Issue by sheyma** [jordandekraker/hippunfold_toolbox#1]
Hi,
many thanks building `hippunfold_toolbox`.

I would like to ask if it is possible to embed the border drawing functionality in matlab (basically the functions  [plot_giftiborders.m](https://github.com/jordandekraker/hippunfold_toolbox/blob/main/Matlab/plot_giftiborders.m) and [surfdat_smooth.m](https://github.com/jordandekraker/hippunfold_toolbox/blob/main/Matlab/surfdat_smooth.m)) into python. 

So the goal would be having a purely python based generated figure with all gifti files (*labels*, *surf*, etc..) like this:
![T1wT2w_bordersALL_PuOr](https://user-images.githubusercontent.com/2557416/201074787-7bfa173c-fba2-45da-8f0f-3884c5cb886c.png)

Thanks in advance!

**Comment by jordandekraker** [comment]
Thanks for the request!

I just added the same function as the matlab version: 3fac83fa99208a05ff5b70392c0ec361fc40cb1e

However, I had some of the same issues as you as in my example: https://github.com/jordandekraker/hippunfold_toolbox/blob/main/test_notebooks/plot_subfield_boundaries.ipynb

matplotlib doesn't seem to understand that it should not render points that are occluded by another surface overtop. If you render the points first and then the surface, then the points become totally occluded. Replacing `scatter` with `plot3D` (after sorting the boundary points), only makes the occulsion issue worse. 

Also some gaps are present where the CA4 boundary wasn't found in this tesselation because it's too narrow. After trying for a while, i don't think there is a clear way around these two issues, and I suspect for this sort of issue we'll eventually have to move away from matplotlib. In the meantime maybe `wb_view` would work?

**Comment by sheyma** [comment]
Hi @jordandekraker,

maybe we should go back one step, and try to reproduce border-plotting in matlab. Because, I suspect that computing borders is not correct, rather than the way they are visualized.

This matlab figure is highly identical to your original publication, using my data (thanks for developing a nicely reproducible pipeline):

![p_MATLAB_foldUnfold](https://user-images.githubusercontent.com/2557416/202283647-286c4a3d-8f6e-4c87-807a-2b3125d5968b.svg)

However, computing borders and plotting on top (with [plot_giftiborders.m](https://github.com/jordandekraker/hippunfold_toolbox/blob/main/Matlab/plot_giftiborders.m) and [surfdat_smooth.m](https://github.com/jordandekraker/hippunfold_toolbox/blob/main/Matlab/surfdat_smooth.m) does not look so good:

![p_MATLAB_foldUnfold_borders](https://user-images.githubusercontent.com/2557416/202284984-edb0d511-79a9-40d5-af81-a2f5ef754780.svg)

So, maybe the smoothing function does something, that it was indeed something specific to your data. 

A good way of testing it: Could you please share your HCP-average **labeling** and **surface** files?

**Comment by jordandekraker** [comment]
What exactly is the issue with this visualization?

If its that the borders break apart at the anterior and posterior edges, that may actually be a helpful feature in showing some uncertainty in those regions. The realworld size of these regions is very tiny and the subfield borders are hard to distinguish even with histology. In unfolded space these get enlarged quite a bit (as you can also see by the large face sizes or individual triangles)

It may also be worth considering Freesurfer for visualization: https://hippunfold.readthedocs.io/en/latest/outputs/visualization.html

**Comment by sheyma** [comment]
Issues with the visualization are 1) a mismatch of borders for CA4 along the hippocampus (Right figure) and 2) abrupt changes of borders at the most anterior and most posterior edges in the unfolded hippocampus (left figure).


> The realworld size of these regions is very tiny and the subfield borders are hard to distinguish even with histology. In unfolded space these get enlarged quite a bit (as you can also see by the large face sizes or individual triangles)

That is a reasonable explanation. Still, I managed to make the borders as close as to your publication here:

![p_subfield_labels_borders_full_JDKSB](https://user-images.githubusercontent.com/2557416/203127254-966efdae-311c-4922-9977-2d78a58d5a2c.svg)

We can close this issue.
Thanks.
