### ISSUE TITLE
Question about projecting fmri signal to hippocampal surface

### ISSUE THREAD

**Issue by oliver-xie** [jordandekraker/hippunfold_toolbox#8]
Hi Jordan,
In the tutorial_fMRI.ipynb  tutorial [1)](https://github.com/jordandekraker/hippunfold_toolbox/blob/main/demos/tutorial_fMRI.ipynb), it is written 
 
> Sample data along a hippocampal surface:
> For fMRI data, resolution is typically >=2mm, and so I recommend using den-2mm surfaces (obtained by adding the flag --output_density 2mm when executing HippUnfold). Otherwise the default den-0p5mm surfaces will work fine, but you may be unnecessarily oversampling the fMRI data.
> 
> for h in range(len(hemi)):
>     for l in range(len(label)):
>         cmd = f'wb_command -volume-to-surface-mapping '\
>             f'tmp/sub-{subject}_ses-{session}_space-nativepro_rsfmri.nii.gz '\
>             f'{hippunfold_dir}/sub-{subject}/surf/sub-{subject}_hemi-{hemi[h]}_space-T1w_den-2mm_label-{label[l]}_midthickness.surf.gii '\
>             f'tmp/sub-{subject}_hemi-{hemi[h]}_space-T1w_den-2mm_label-{label[l]}_desc-rsmfri.func.gii '\
>             f'-enclosing'
>         !{cmd}

I am not sure why enclosing is chosen to be the resampling method as my understanding is enclosing acts like nearest neighbor interpolation, which is much more crude than trilinear or cubic, see [2)](https://link.springer.com/article/10.1007/s00429-022-02536-4).

> The Enclosing method, for instance, simply assigns to each vertex the data of the voxel inside which it lies. The Trilinear approach involves doing a linear interpolation of the data from the eight voxels closest to the vertex, and the Cubic algorithm employs cubic splines 

Moreover, in [2)](https://link.springer.com/article/10.1007/s00429-022-02536-4), authors also compared the resampling methods, and found Enclosing introduced the worst spurious local connectivity profile. Is there any specific reason to choose enclosing here?
Thanks,
Oliver

**Comment by jordandekraker** [comment]
Hi Oliver, thanks for your interest in this point

We chose enclosing in this case since its most conservative. For very large voxel sizes (e.g. 3mm), a trilinear interpolation could include a lot of signal from areas outside the hippocampus, including CSF or even choroid plexus. For smaller voxels you may not be worried about this, and may instead be more interested in getting the highest signal level possible, so trilinear may be better. This isn't a strong recommendation though, just an example, so feel free to use the interpolation method you find most appropriate!

**Comment by oliver-xie** [comment]
Thanks for the explanation!
